### ISSUE TITLE
Very Large file artifact uploading errors out

### ISSUE THREAD

**Issue by chtaylo2** [pulp/pulpcore#5307]
When calling the following, seeing it error out on very large ISO files. I'm not seeing it error on anything less then 1GB

```
  - name: "Upload artifact :: {{ artifact }}"
    pulp.squeezer.artifact:
      file: "{{ artifact }}"
      chunk_size: 10000000
      state: present
    register: local_artifact_info
```
Example: Uploading an [AlmaLinux 9.3](https://repo.almalinux.org/almalinux/9.3/isos/x86_64/AlmaLinux-9.3-x86_64-dvd.iso) ISO that's 10GB, it uploads all the chucks and then errors during the upload commit. The same operations using the pulp-cli is working.

Attached are the sanitized output for both Pulp CLI and Squeezer.

[large_upload-PULP-SQUEEZER.txt](https://github.com/pulp/squeezer/files/15083171/large_upload-PULP-SQUEEZER.txt)
[large_upload-PULP-CLI.txt](https://github.com/pulp/squeezer/files/15083109/large_upload-PULP-CLI.txt)

Once the /commit API is called, a few seconds later I see:
`INFO: Task 018f0cb0-7413-71e6-a0bf-ad917d8f0be1 failed ([Errno 2] No such file or directory: '/var/lib/pulp/media/upload/018f0ca2-f862-77d9-8161-ed52a8e97f69')`

Another important note, that file name above appeared in that location just a few seconds before the error.
