### ISSUE TITLE
Provide general feature and workflow matrix for plugins

### ISSUE THREAD

**Issue by pedro-psb** [pulp/pulpcore#5593]
While fixing some links in pulp-oci-images, I've came across a reference to ["Workflows and Use Cases"](https://github.com/pulp/pulpcore/blob/main/docs/workflows/index.rst), which was a set of pages on pulpcore legacy docs. On docs migration, while moving some of these pages, we didnt preserve the notion of a workflow in pulpcore docs.

If I was reading the pulp-oci-images and got to this point (the link is in a section called "Try out a workflow"), I would expect to go to a page with small descriptions of some workflows and links to concrete plugin-implementation for them. And possibly a matrix table, similar to the matrix request for dependencies (https://github.com/pulp/pulpcore/issues/5573), but maybe a little harder to automate.

## Problem

No definitive reference for available features and workflows across plugins.

## Initial Approach

What I see as possible first steps are:
- formalize better what "feature" and "workflow" mean
- have a compreehensive list of features and workflows.
- group features in a useful way

As a starting point, I tried to organize the titles mentioned in the "Workflow and Use Cases" page linked above.

```yaml
# definition
workflow: high-level usecases which relies on a set of features
feature: objective capability provided by Pulp
    - builtin: doesn't requires per-plugin-support. 
    - extensions: requires per-plugin-support.

# initial triage
workflows:
    - upload-publish
    - promotion 
features:
    - built-in:
        - user:
            - complex-filtering
            - exposing-content
            - labels
            - repo-versioning
        - admin:
            - repairing-pulp
            - reclaim-disk-space
            - plugin-removal
            - scheduling-tasks
            - troubleshooting
    - extension (requires plugin support):
        - domains-multi-tenancy
        - sign-metadata
        - import-export
        - alternate-content-sources
        - on-demand-downloading
```

## Further steps

Having a compreehensive list of that, we can:
- Create a simple Features and Workflows page manually
- Create some system to semi-automate this matrix:
  E.g: each plugin repository can contain a feature-set manifesto which is used by pulp-docs to generate the matrix.
  This manifesto can include things like tech-preview status, version info (included, modified and deprecated), etc.
